# Generated by Django 4.0.3 on 2022-04-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Titulos',
            new_name='titulo',
        ),
    ]
